---
#
# Ansible managed
#
repository:
  description: The purpose of this role is to configure common things on your system.
  homepage: https://robertdebock.nl/
  topics: common, hosts, hostname, server, system, ansible, molecule, tox, playbook, hacktoberfest
