---
# handlers file for common

- name: gather facts
  setup:
  become: no

- name: reload network manager
  service:
    name: NetworkManager
    state: reloaded

- name: reboot
  reboot:
  when:
    - common_reboot | bool
